name: Run KJnews

on:
  schedule:
    # UTC+8 8~20 -> UTC+0 0~12, run every two hours.
    - cron: "0 0-12/2 * * *"
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run KJnews
        run: python main.py
        env: 
          LINE_NOTIFY_ID: ${{ secrets.LINE_NOTIFY_ID }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          MESSAGE_POST_URL: ${{ secrets.MESSAGE_POST_URL }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GOOGLE_SHEETS_KEY: ${{ secrets.GOOGLE_SHEETS_KEY }}
          GS_CREDENTIALS: ${{ secrets.GS_CREDENTIALS }}
